theme: jekyll-theme-primerpages
title: PrimerPages Site
description: Theme built with jekyll-theme-primerpages
image: /assets/img/social-preview.png

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "docs"
      toc: true
      index: "/"

########################## THEME SETTINGS ##########################

##########################
# Style settings 
##########################
# # The style of the website
style: appbar # One of "stacked", "sidebar", "topbar", "appbar"
# # The user/project avatar.  If not set the avatar of the project owner will be used.
# user_image: /assets/img/user-image.jpg
# # The site logo/favicon
# favicon: /img/assets/appbar-icon.png
# # The themes to use for dark and light
# dark_theme: dark_dimmed
# light_theme: light
# # Optional custom background image and overlay
# background:
#   image: /image/assets/background-img.jpg
#   overlay: rgba(0, 0, 0, 0.7)
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

# # Optional custom header colors
# header:
#   color: "#4051b5"
#   text: "rgba(255,255,255,0.7)"
#   accent: "#ffffff"

repo_info: true # Show the information for the source of this project
user_metadata: true # Show the metadata associated with the user
profile_link: true # Show a link to the github profile for the user
edit_url: "https://www.github.com/athackst/dockerfiles/edit/main/"
##########################
# Social media settings
##########################
# icon_color: "#959da5" # The color of the social media icons on the site
# social_media: # Your social media accounts
  # behance: your_username
  # dribbble: your_username
  # docker: your_username
  # facebook: your_username
  # github: PrimerPages
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mail: email@address
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # threads: your_username
  # tiktok: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # vscode: your_username
  # youtube: your_username
  # x: your_username

##########################
# Navigation links
##########################
# nav:
#   - name: Blog
#     url: /blog
#   - name: Documentation
#     url: /docs

##########################
# Repository link
##########################
repository: "PrimerPages/primerpages-docs"

########################## PLUGIN SETTINGS ##########################
plugins:
  - jekyll-awesome-nav
  - jekyll-gfm-admonitions
  - jekyll-octicons
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji

awesome_nav:
  enabled: true
  root: ""
  nav_filename: .nav.yml

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true

toc:
  max_level: 2

relative_links:
  enabled:     true
  collections: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/
  - .venv/
